# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, modulesPath, ... }:

{
  imports =
    [
      "${modulesPath}/installer/scan/not-detected.nix"
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "uas" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "helios/os";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/E0F4-CB73";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    {
      device = "helios/os/nix";
      fsType = "zfs";
    };

  fileSystems."/etc" =
    {
      device = "helios/os/etc";
      fsType = "zfs";
    };

  fileSystems."/root" =
    {
      device = "helios/os/root";
      fsType = "zfs";
    };

  fileSystems."/var" =
    {
      device = "helios/os/var";
      fsType = "zfs";
    };

  fileSystems."/nix/store" =
    {
      device = "helios/os/nix/store";
      fsType = "zfs";
    };

  fileSystems."/var/cache" =
    {
      device = "helios/os/var/cache";
      fsType = "zfs";
    };

  fileSystems."/var/db" =
    {
      device = "helios/os/var/db";
      fsType = "zfs";
    };

  fileSystems."/var/empty" =
    {
      device = "helios/os/var/empty";
      fsType = "zfs";
    };

  fileSystems."/var/log" =
    {
      device = "helios/os/var/log";
      fsType = "zfs";
    };

  fileSystems."/var/tmp" =
    {
      device = "helios/os/var/tmp";
      fsType = "zfs";
    };

  swapDevices = [ ];

  nix.settings.max-jobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
