#!/bin/sh

list_snapshots() {
    zfs list -t snapshot -o name $1 | grep $2 | tac | tail -n +$(($3 + 1)) | sed 's/.*@//' | sed -z 's/\n/,/g'
}

if [ $# -ne 6 ]; then
    echo "usage: $0 <dataset> <frequent> <hourly> <daily> <weekly> <monthly>"
    exit 1
fi

for dataset in $(zfs list -r -o name $1 | tail -n +2); do
    # Remove “system” snapshots.
    valid_state=$(list_snapshots $dataset valid-state 0)
    update=$(list_snapshots $dataset update 0)
    sys_snaps=$valid_state$update

    # Keep only one syncoid snapshot per backup pool.
    old_helios=$(list_snapshots $dataset syncoid_helios_saturne 1)
    old_titan=$(list_snapshots $dataset syncoid_titan_saturne 1)
    old_tethys=$(list_snapshots $dataset syncoid_tethys_saturne 1)
    old_backup=$old_helios$old_titan$old_tethys

    # Keep auto-snapshots as configured.
    old_frequent=$(list_snapshots $dataset frequent $2)
    old_hourly=$(list_snapshots $dataset hourly $3)
    old_daily=$(list_snapshots $dataset daily $4)
    old_weekly=$(list_snapshots $dataset weekly $5)
    old_monthly=$(list_snapshots $dataset monthly $6)
    old_auto=$old_frequent$old_hourly$old_daily$old_weekly$old_monthly

    old_snapshots=$(echo $sys_snaps$old_backup$old_auto | sed 's/.$//')

    if [ "$old_snapshots" != "" ]; then
      zfs destroy -v $dataset@$old_snapshots
    fi
done
