#!/bin/sh

set -e

if [ $# -ne 3 ]; then
    echo "usage: $0 <store-paths.xz> <upstream_binary_cache> <local_binary_cache>"
    exit 1
fi

paths=$1
upstream=$2
mirror=$3

printf "\n\e[32m=> Copy the binary cache to $mirror...\e[0m\n\n"

# Build the local binary cache.
mkdir -p "$mirror"
xzcat "$paths" | xargs nix copy --store $upstream --to "file://$mirror"

printf "\n\e[32m\e[1mThe mirror is up to date!\e[0m\n\n"
