#!/bin/sh

set -e

# Extand the display.
xrandr --output DP-0 --auto
xrandr --output DP-1.1 --auto --right-of DP-0
xrandr --output DP-1.2 --auto --right-of DP-1.1
xrandr --dpi 212

# Switch the configuration.
touch $HOME/.local/share/is_docked
ln -sf sxhkdrc_docked $HOME/.config/sxhkd/sxhkdrc

# Reload the desktop environment.
killall sxhkd
$HOME/.config/bspwm/bspwmrc
pkill -USR1 termite
systemctl --user restart polybar
