#!/bin/sh

if [ $UID -ne 0 ]; then
    echo "You must execute this command as root."
    exit 1
fi

printf "\n\e[32m=> Snapshotting saturne...\e[0m"

snapshot_time=$(date --utc --iso-8601=seconds | sed s/+00:00/Z/)
snapshot="backup-saturne_$snapshot_time"
zfs snapshot -r saturne@$snapshot

printf "\n\e[32m=> Creating bookmarks of the snapshots...\e[0m"

for dataset in $(zfs list -Hro name saturne); do
    zfs bookmark $dataset@$snapshot "$dataset#$snapshot"
done

printf "\n\e[32m=> Backing up the ZFS datasets...\e[0m\n\n"

syncoid --no-sync-snap --sendoptions=wp -r saturne titan/saturne

printf "\n\e[32m=> Cleaning old snapshots...\e[0m\n\n"

zfs-clean-snapshots saturne 4 48 7 4 24
zfs-clean-snapshots titan/saturne 4 48 7 4 24

printf "\n\e[32m=> Backing up the boot partition...\e[0m\n\n"

mkdir /boot-backup
mount /dev/disk/by-label/boot-backup /boot-backup
rsync -a --progress --delete-before /boot/ /boot-backup/
umount /boot-backup
rmdir /boot-backup

printf "\n\e[32m\e[1mBackup complete!\e[0m\n\n"
